# Generated by Django 3.2.6 on 2021-08-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_stripe_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer',
        ),
    ]
