# Generated by Django 3.2.6 on 2021-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='user_profile',
            field=models.CharField(default='', max_length=200),
        ),
    ]
