# Generated by Django 3.2.6 on 2021-08-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='product_size',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
