# Generated by Django 3.2.6 on 2021-08-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210817_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglineitem',
            old_name='booking_total',
            new_name='lineitem_total',
        ),
        migrations.AlterField(
            model_name='bookinglineitem',
            name='product_size',
            field=models.CharField(default='', max_length=4),
        ),
    ]
