# Generated by Django 3.2.6 on 2021-08-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210819_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglineitem',
            name='product_size',
        ),
    ]
